Vagrant.configure("2") do |config|
  config.vm.define :win do |win_config|
    win_config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 1
        vb.name = "Windows7-pro-x64"
    end
    win_config.vm.box = "mrlesmithjr/windows-7"
    win_config.vm.box_version = "20171129.0"
    win_config.vm.communicator = "winrm"
    win_config.vm.network "private_network", ip: "192.168.50.100"
    win_config.vm.provision "shell", path: "../common/install-choco.bat", privileged: true
    win_config.vm.provision "shell", path: "../common/update-powershell.ps1", privileged: true
    win_config.vm.provision "shell", path: "../common/ConfigureRemotingForAnsible.ps1", privileged: true
  end  
end