choco install notepadplusplus -y
choco install git.install -y
choco install 7zip -y
choco install firefox -y
choco install googlechrome -y
choco install teamviewer -y
choco install vagrant -y
choco install #github -y
choco install visualstudiocode -y 
choco install pgdmin4 -y
choco install sourcetree -y
choco install sumatrapdf -y
choco install irfanview -y
choco install keepass -y
choco install nuget.commandline -y